// theme
export enum SIZES {
  SMALL = "small",
  MEDIUM = "medium",
  LARGE = "large",
  XLARGE = "xlarge",
}

// filetree
export enum FILETREE_TYPES {
  FOLDER = "folder",
  BINDER = "binder",
  STUDY_SET = "study-set",
}

// URL params
export enum TAB_TYPE {
  FLASHCARDS = "flashcards",
  NOTES = "notes",
}

export enum STUDY_MODE_TYPES {
  SPACED_REPETITION = "spaced-repetition",
  FREE_STUDY = "free-study",
}

// modals
export enum MODAL_FOOTER_TYPE {
  PRIMARY = "primary",
  DELETE = "delete",
}

export enum MODAL_TYPE {
  // see https://www.nngroup.com/articles/popups/ for further reference on modal types
  MODAL_LIGHTBOX = "modal-lightbox", // includes lightbox and you can't interact with the background
  MODAL_NON_LIGHTBOX = "modal-non-lightbox", // no lightbox and you can't interact with the background
  NON_MODAL_NON_LIGHTBOX = "non-modal-non-lightbox", // no lightbox and can interact with the background
  NON_MODAL_LIGHTBOX = "non-modal-lightbox", // includes lightbox and you can interact with the background
  TOOL_TIP = "non-modal-non-lightbox",
}

// buttons
export enum BUTTON_TYPES {
  SUBMIT = "submit",
  BUTTON = "button",
}

export enum BUTTON_THEME {
  PRIMARY = "primary",
  SECONDARY = "secondary",
  DANGER = "danger",
}

// note-taking

export enum BLOCK_TYPES {
  UNSTYLED = "unstyled",
  HEADER_ONE = "header-one",
  HEADER_TWO = "header-two",
  HEADER_THREE = "header-three",
  BULLETED_LIST = "unordered-list-item",
  NUMBERED_LIST = "ordered-list-item",
  QUOTE = "blockquote",
  DIVIDER = "divider",
  TODO = "to-do",
  TOGGLE = "toggle",
}

export enum LIGHT_THEME_FONT_COLORS {
  FONT_COLOR_2C2C31 = "FONT_COLOR_2C2C31",
  FONT_COLOR_00B6CE = "FONT_COLOR_00B6CE",
  FONT_COLOR_E81123 = "FONT_COLOR_E81123",
  FONT_COLOR_F7630D = "FONT_COLOR_F7630D",
  FONT_COLOR_FABD14 = "FONT_COLOR_FABD14",
  FONT_COLOR_0F893E = "FONT_COLOR_0F893E",
  FONT_COLOR_3971D1 = "FONT_COLOR_3971D1",
  FONT_COLOR_4B0082 = "FONT_COLOR_4B0082",
  FONT_COLOR_AC008C = "FONT_COLOR_AC008C",
  FONT_COLOR_84939A = "FONT_COLOR_84939A",
}

export enum DARK_THEME_FONT_COLORS {
  FONT_COLOR_F0F0F0 = "FONT_COLOR_F0F0F0",
  FONT_COLOR_0094CE = "FONT_COLOR_0094CE",
  FONT_COLOR_FB7575 = "FONT_COLOR_FB7575",
  FONT_COLOR_FF9B60 = "FONT_COLOR_FF9B60",
  FONT_COLOR_FFD45C = "FONT_COLOR_FFD45C",
  FONT_COLOR_74E092 = "FONT_COLOR_74E092",
  FONT_COLOR_87C25B = "FONT_COLOR_87C25B",
  FONT_COLOR_CA8BF7 = "FONT_COLOR_CA8BF7",
  FONT_COLOR_FF81DB = "FONT_COLOR_FF81DB",
  FONT_COLOR_C1C1C1 = "FONT_COLOR_C1C1C1",
}

export enum LIGHT_THEME_BACKGROUND_COLORS {
  BACKGROUND_COLOR_FFFFFF = "BACKGROUND_COLOR_FFFFFF",
  BACKGROUND_COLOR_FBE4E4 = "BACKGROUND_COLOR_FBE4E4",
  BACKGROUND_COLOR_FAEBDD = "BACKGROUND_COLOR_FAEBDD",
  BACKGROUND_COLOR_FBF3DB = "BACKGROUND_COLOR_FBF3DB",
  BACKGROUND_COLOR_DDEDEA = "BACKGROUND_COLOR_DDEDEA",
  BACKGROUND_COLOR_DDEBF1 = "BACKGROUND_COLOR_DDEBF1",
  BACKGROUND_COLOR_EAE4F2 = "BACKGROUND_COLOR_EAE4F2",
  BACKGROUND_COLOR_F4DFEB = "BACKGROUND_COLOR_F4DFEB",
  BACKGROUND_COLOR_EBECED = "BACKGROUND_COLOR_EBECED",
  BACKGROUND_COLOR_E9E5E3 = "BACKGROUND_COLOR_E9E5E3",
}

export enum DARK_THEME_BACKGROUND_COLORS {
  BACKGROUND_COLOR_2F3437 = "BACKGROUND_COLOR_2F3437",
  BACKGROUND_COLOR_67371A = "BACKGROUND_COLOR_67371A",
  BACKGROUND_COLOR_594A3A = "BACKGROUND_COLOR_594A3A",
  BACKGROUND_COLOR_59563B = "BACKGROUND_COLOR_59563B",
  BACKGROUND_COLOR_195028 = "BACKGROUND_COLOR_195028",
  BACKGROUND_COLOR_28456D = "BACKGROUND_COLOR_28456D",
  BACKGROUND_COLOR_523271 = "BACKGROUND_COLOR_523271",
  BACKGROUND_COLOR_5A2F51 = "BACKGROUND_COLOR_5A2F51",
  BACKGROUND_COLOR_666666 = "BACKGROUND_COLOR_666666",
  BACKGROUND_COLOR_434040 = "BACKGROUND_COLOR_434040",
}

export enum TEXT_STYLES {
  BOLD = "BOLD",
  ITALIC = "ITALIC",
  UNDERLINE = "UNDERLINE",
  STRIKETHROUGH = "STRIKETHROUGH",
  ALIGN_CENTER = "ALIGN_CENTER",
  ALIGN_LEFT = "ALIGN_LEFT",
  ALIGN_RIGHT = "ALIGN_RIGHT",
  SUBSCRIPT = "SUBSCRIPT",
  SUPERSCRIPT = "SUPERSCRIPT",
  REMOVE_FORMATTING = "REMOVE_FORMATTING",
  INVALID = "INVALID",

  // light theme font
  FONT_COLOR_2C2C31 = "FONT_COLOR_2C2C31",
  FONT_COLOR_00B6CE = "FONT_COLOR_00B6CE",
  FONT_COLOR_E81123 = "FONT_COLOR_E81123",
  FONT_COLOR_F7630D = "FONT_COLOR_F7630D",
  FONT_COLOR_FABD14 = "FONT_COLOR_FABD14",
  FONT_COLOR_0F893E = "FONT_COLOR_0F893E",
  FONT_COLOR_3971D1 = "FONT_COLOR_3971D1",
  FONT_COLOR_4B0082 = "FONT_COLOR_4B0082",
  FONT_COLOR_AC008C = "FONT_COLOR_AC008C",
  FONT_COLOR_84939A = "FONT_COLOR_84939A",

  // dark theme font
  FONT_COLOR_F0F0F0 = "FONT_COLOR_F0F0F0",
  FONT_COLOR_0094CE = "FONT_COLOR_0094CE",
  FONT_COLOR_FB7575 = "FONT_COLOR_FB7575",
  FONT_COLOR_FF9B60 = "FONT_COLOR_FF9B60",
  FONT_COLOR_FFD45C = "FONT_COLOR_FFD45C",
  FONT_COLOR_74E092 = "FONT_COLOR_74E092",
  FONT_COLOR_87C25B = "FONT_COLOR_87C25B",
  FONT_COLOR_CA8BF7 = "FONT_COLOR_CA8BF7",
  FONT_COLOR_FF81DB = "FONT_COLOR_FF81DB",
  FONT_COLOR_C1C1C1 = "FONT_COLOR_C1C1C1",

  // light theme background
  BACKGROUND_COLOR_FFFFFF = "BACKGROUND_COLOR_FFFFFF",
  BACKGROUND_COLOR_FBE4E4 = "BACKGROUND_COLOR_FBE4E4",
  BACKGROUND_COLOR_FAEBDD = "BACKGROUND_COLOR_FAEBDD",
  BACKGROUND_COLOR_FBF3DB = "BACKGROUND_COLOR_FBF3DB",
  BACKGROUND_COLOR_DDEDEA = "BACKGROUND_COLOR_DDEDEA",
  BACKGROUND_COLOR_DDEBF1 = "BACKGROUND_COLOR_DDEBF1",
  BACKGROUND_COLOR_EAE4F2 = "BACKGROUND_COLOR_EAE4F2",
  BACKGROUND_COLOR_F4DFEB = "BACKGROUND_COLOR_F4DFEB",
  BACKGROUND_COLOR_EBECED = "BACKGROUND_COLOR_EBECED",
  BACKGROUND_COLOR_E9E5E3 = "BACKGROUND_COLOR_E9E5E3",

  // dark theme background
  BACKGROUND_COLOR_2F3437 = "BACKGROUND_COLOR_2F3437",
  BACKGROUND_COLOR_67371A = "BACKGROUND_COLOR_67371A",
  BACKGROUND_COLOR_594A3A = "BACKGROUND_COLOR_594A3A",
  BACKGROUND_COLOR_59563B = "BACKGROUND_COLOR_59563B",
  BACKGROUND_COLOR_195028 = "BACKGROUND_COLOR_195028",
  BACKGROUND_COLOR_28456D = "BACKGROUND_COLOR_28456D",
  BACKGROUND_COLOR_523271 = "BACKGROUND_COLOR_523271",
  BACKGROUND_COLOR_5A2F51 = "BACKGROUND_COLOR_5A2F51",
  BACKGROUND_COLOR_666666 = "BACKGROUND_COLOR_666666",
  BACKGROUND_COLOR_434040 = "BACKGROUND_COLOR_434040",
}
